version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
